config/routes.rb
Rails.application.routes.draw do
  resources :workouts do
    scope module: :workouts do
      resources :exercises, only: [:new, :create, :show, :edit]
    end
  end

  resources :exercise_types, only: [:new, :create]

  get '/activity', to: 'workouts#index'
  root to: 'workouts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calisthenics_exercise.rb
class CalisthenicsExercise < ApplicationRecord
  include Exercisable
end

app/models/cardio_exercise.rb
class CardioExercise < ApplicationRecord
  include Exercisable

  def total_km
    sets.pluck(:distance, :reps)
        .compact
        .map { |distance, reps| distance * reps }
        .sum
  end

  def total_seconds
    sets.pluck(:start_time, :finish_time)
        .compact
        .map { |start_time, finish_time| finish_time - start_time }
        .sum
        .seconds.to_i
  end
end

app/models/concerns/exercisable.rb
module Exercisable
  extend ActiveSupport::Concern

  included do
    has_one :exercise, as: :exercisable, dependent: :destroy
    has_one :exercise_type, through: :exercise
    has_many :exercise_sets, through: :exercise

    alias :sets :exercise_sets
  end
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :workout
  belongs_to :exercise_type
  belongs_to :exercisable, polymorphic: true
  has_many :exercise_sets

  delegate :name, :category, to: :exercise_type
  alias :sets :exercise_sets

  CLASS_NAMES = {
    'resistance' => 'ResistanceExercise',
    'calisthenics' => 'CalisthenicsExercise',
    'cardio' => 'CardioExercise'
  }.freeze

  def total_reps
    sets.pluck(:reps).sum
  end
end

app/models/exercise_set.rb
class ExerciseSet < ApplicationRecord
  belongs_to :exercise

  def duration_in_seconds
    return (Time.current - start_time).round if finish_time.blank?

    (finish_time - start_time).round
  end
end

app/models/exercise_type.rb
class ExerciseType < ApplicationRecord
  has_many :exercises

  enum category: {
    'calisthenics': 'calisthenics',
    'cardio': 'cardio',
    'resistance': 'resistance'
  }
end

app/models/resistance_exercise.rb
class ResistanceExercise < ApplicationRecord
  include Exercisable

  def total_kg
    sets.pluck(:weight, :reps)
        .compact
        .map { |weight, reps| weight * reps }
        .sum
  end
end

app/models/workout.rb
class Workout < ApplicationRecord
  has_many :exercises
  has_many :exercise_types, through: :exercises

  has_many :resistance_exercises, through: :exercises, source: :exercisable, source_type: 'ResistanceExercise'
  has_many :cardio_exercises, through: :exercises, source: :exercisable, source_type: 'CardioExercise'
  has_many :calisthenics_exercises, through: :exercises, source: :exercisable, source_type: 'CalisthenicsExercise'

  validates :state, presence: true, inclusion: { in: ['started', 'completed', 'deleted'] }
  validates :start_time, presence: true
  validate :finish_time_is_after_start_time, if: -> { start_time.present? && finish_time.present? }

  enum state: {
    started: 'started',
    completed: 'completed',
    deleted: 'deleted'
  }

  def duration_in_seconds
    return (Time.current - start_time) if finish_time.nil?

    finish_time - start_time
  end

  private

  def finish_time_is_after_start_time
    errors.add(:finish_time, 'should be after start time') if finish_time <= start_time
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exercise_types_controller.rb
class ExerciseTypesController < ApplicationController
  def new
    @exercise_type_form ||= BusinessModels::ExerciseType.new
  end

  def create
    @exercise_type_form = BusinessModels::ExerciseType.new(exercise_type_params)
    result = Interactors::ExerciseTypes::Create.call(exercise_type_form: @exercise_type_form)

    if result.success?
      current_workout = Workout.find_by(state: 'started')
      redirect_to new_workout_exercise_path(current_workout)
    else
      flash.now[:error] = result.error
      render 'exercise_types/new'
    end
  end

  private

  def exercise_type_params
    params.require(:business_models_exercise_type).permit(:name, :targets, :category)
  end
end

app/controllers/workouts/exercises_controller.rb
module Workouts
  class ExercisesController < Workouts::MainController
    before_action :set_exercise, only: [:show]

    def new
      @exercise_form = BusinessModels::Workouts::Exercise.new(workout: @workout)
    end

    def create
      exercise_type = ExerciseType.find_by(id: exercise_params[:exercise_type_id])
      @exercise_form = BusinessModels::Workouts::Exercise.new(workout: @workout, exercise_type: exercise_type)

      result = Interactors::Exercises::Create.call(exercise_form: @exercise_form)

      if result.success?
        exercise = result.exercise

        case exercise.exercisable_type
        when 'ResistanceExercise'
          redirect_to workout_resistance_exercise_path(@workout, exercise.exercisable_id)
        when 'CardioExercise'
          redirect_to workout_cardio_exercise_path(@workout, exercise.exercisable_id)
        when 'CalisthenicsExercise'
          redirect_to workout_calisthenics_exercise_path(@workout, exercise.exercisable_id)
        end
      else
        render :new
      end
    end

    def show
    end

    private

    def exercise_params
      params.require(:business_models_workouts_exercise).permit(:exercise_type_id)
    end

    def set_exercise
      @exercise = Exercise.find_by(exercisable_id: params[:id])
    end
  end
end

app/controllers/workouts/main_controller.rb
module Workouts
  class MainController < ApplicationController
    before_action :set_workout

    private

    def set_workout
      @workout = Workout.find(params[:workout_id])
    end
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_current_workout
  before_action :set_workout, only: [:show, :destroy]

  def index
    @workouts = Workout.order(start_time: :desc)
  end

  def new
  end

  def show
    @exercises = @workout.exercises
  end

  def create
    @workout = Workout.new(start_time: Time.now)

    if @workout.save
      flash[:success] = 'Starting new workout!'
      redirect_to @workout
    else
      flash[:failure] = 'Failed to create workout'
      render 'new'
    end
  end

  def set_current_workout
    @current_workout ||= Workout.started.last
  end

  private

    def set_workout
      @workout = Workout.find params[:id]
    end

    def workout_params
      params.require(:workout).permit(:start_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_svg(name, options = {})
    size_classes = {
      '2xsmall': '1.25rem * 1.25rem',
      'xsmall': '2rem * 2rem',
      'small': '3rem * 3rem',
      'medium': '6rem * 6rem',
      'large': '8rem * 8rem'
    }

    options[:title] = name.underscore.humanize
    options[:class] = options.fetch(:class, 'fill-current text-green-900')
    options[:aria] = true
    options[:nocomment] = true
    options[:size] = size_classes[options.fetch(:size, 'small').to_sym]

    file_name = "#{name}.svg"

    inline_svg_tag(file_name, options)
  end
end

app/helpers/exercise_types_helper.rb
module ExerciseTypesHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
  def page_title
    app_title = 'Undo'
    prefix = content_for?(:page_title) ? "#{content_for(:page_title)} | " : ''
    content_tag(:title, prefix.concat(app_title))
  end
end

app/helpers/workouts/resistance_exercises_helper.rb
module Workouts::ResistanceExercisesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercise_types/new.html.erb
<h1 class="text-2xl mb-6">New Exercise Type</h1>

<%= form_with(model: @exercise_type_form, url: exercise_types_path, local: true) do |f| %>
  <%= render 'shared/form_errors', object: @exercise_type_form %>
  <div class="form-group">
    <%= f.label :name%>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :category %>
    <%= f.select :category, ExerciseType.categories.keys.map { |k| [k.capitalize, k] }, include_blank: 'Choose...', class: 'form-control' %>
  </div>

  <div class="form-group mb-0">
    <%= f.label :targets %>
    <%= f.text_field :targets %>
  </div>

  <div class="flex justify-center">
    <%= f.submit 'Create', class: "btn-primary" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= page_title %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render 'shared/meta_tags' %>

    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="h-screen min-h-screen font-sans bg-gray-200 box-border p-4">
    <div class="main h-full flex-1">
      <%= render 'shared/flashes' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if flash[:error].present? %>
  <div class="alert alert-error flex justify-between w-full bg-red-200 p-2 mb-6 items-center shadow-md">
    <div class="text-red-700 font-semibold text-sm">
      <%= flash[:error] %>
    </div>
    <%= render_svg('icons/close', size: '2xsmall', class: 'fill-current text-red-700') %>
  </div>
<% end %>

<% if flash[:notice].present? %>
  <div class="alert alert-notice flex justify-between w-full bg-yellow-200 p-2 mb-6 items-center shadow-md">
    <div class="text-orange-600 font-semibold text-sm">
      <%= flash[:notice] %>
    </div>
    <%= render_svg('icons/close', size: '2xsmall', class: 'fill-current text-orange-600') %>
  </div>
<% end %>

<% if flash[:success].present? %>
  <div class="alert alert-success flex justify-between w-full bg-blue-200 p-2 mb-6 items-center shadow-md">
    <div class="text-blue-800 font-semibold text-sm">
      <%= flash[:success] %>
    </div>
    <%= render_svg('icons/close', size: '2xsmall', class: 'fill-current text-blue-800') %>
  </div>
<% end %>

app/views/shared/_form_errors.html.erb
<% if object.errors.any? %>
  <div class='bg-red-100 border-red-600 border-2 p-3 mb-4'>
    <h4 class="font-semibold mb-2">The form contains <%= pluralize(object.errors.count, 'error') %>:</h4>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li class="italic"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_meta_tags.html.erb
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Josh Teperman">
    <meta name="description" content="Personal Health and Fitness Tracker">
    <meta property="og:title" content="Undo">
    <meta property="og:description" content="Personal Health and Fitness Tracker">
    <meta property="og:image" content="">
    <meta property="og:url" content="">
    <meta property="og:site_name" content="Undo">
    <meta name="twitter:card" content="">
    <meta name="twitter:image:alt" content="image description">

app/views/workouts/exercises/new.html.erb
<h1 class="text-2xl mb-6">New Exercise</h1>

<%= form_with(model: @exercise_form, url: workout_exercises_path) do |f| %>
  <div class="form-group mb-0">
    <%= f.label :exercise_type_id %>
    <%= f.collection_select :exercise_type_id, ExerciseType.all, :id, :name, include_blank: 'Choose...' %>
    <span class="text-xs text-gray-600 ml-2 mt-1 block italic">search or type to add a new exercise to this workout</span>
  </div>
  <div class="flex justify-center">
    <%= f.submit 'Add Exercise', class: "btn-primary" %>
  </div>
<% end %>
<%= link_to 'Create a new type of exercise', new_exercise_type_path, class: 'btn-text w-full text-center inline-block text-sm uppercase font-semibold' %>

app/views/workouts/exercises/show.html.erb
<h4><%= "#{@exercise.exercisable_type.titleize}: #{@exercise.name}" %></h4>

app/views/workouts/index.html.erb
<%= content_for :page_title, 'Activity' %>

<% if @current_workout.present? %>
  <div class="w-full bg-green-100 flex flex-col justify-center items-center p-6">
    <h4 class='mb-4'>You have an ongoing workout!</h4>
    <%= link_to 'Resume', workout_path(@current_workout), class: 'btn-primary' %>
  </div>
<% end %>
<div class="page flex flex-col items-center justify-between py-4">
  <% if @workouts.present? %>
    <%= render Workouts::SummaryComponent.with_collection(@workouts) %>
  <% else %>
  <% end %>
</div>

app/views/workouts/new.html.erb
<%= content_for :page_title, 'Workout' %>

<div class="flex w-full h-full items-center justify-center">
  <% if @current_workout %>
    <div class="flex flex-col items-center">
      <span class="text-lg mb-6">You have an ongoing workout!</span>
      <%= link_to 'Resume', @current_workout, class: 'btn-primary' %>
    </div>
  <% else %>
    <%= link_to 'New Workout', workouts_path, method: :post, class: 'btn-primary' %>
  <% end %>
</div>

app/views/workouts/show.html.erb
<%= content_for :page_title, 'Workout' %>
<div class="flex flex-col items-center justify-between mb-6">
  <div class="w-full h-auto">
    <%= render Workouts::ExercisePreviewComponent.with_collection(@exercises, workout: @workout) %>
  </div>
  <% if @current_workout.present? %>
    <%= link_to 'Add Exercise', new_workout_exercise_path(@current_workout), local: true, class: "btn-primary mt-8 mb-10 shadow-xl" %>
  <% end %>
</div>